package com.zengxh.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zengxh.framework_demo.Model.Speaker;

import com.zengxh.greendao.db.SpeakerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig speakerDaoConfig;

    private final SpeakerDao speakerDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        speakerDaoConfig = daoConfigMap.get(SpeakerDao.class).clone();
        speakerDaoConfig.initIdentityScope(type);

        speakerDao = new SpeakerDao(speakerDaoConfig, this);

        registerDao(Speaker.class, speakerDao);
    }
    
    public void clear() {
        speakerDaoConfig.clearIdentityScope();
    }

    public SpeakerDao getSpeakerDao() {
        return speakerDao;
    }

}
